import fs from 'node:fs';
import path from 'node:path';

test('styles rich table editor surface and edge handles like the WorkPlan implementation', () => {
  const cssPath = path.resolve(__dirname, 'RichTable.css');
  const css = fs.readFileSync(cssPath, 'utf8');

  expect(css).toContain('.rt-container {');
  expect(css).toContain('padding: 4px 0;');
  expect(css).toContain('.rt-scroll-shell {');
  expect(css).toContain('overflow-x: auto;');
  expect(css).toContain('.rt-scroll-track {');
  expect(css).toContain('min-width: var(--rt-track-min-width, 100%);');
  expect(css).toContain('width: fit-content;');
  expect(css).toContain('max-width: 100%;');
  expect(css).toContain('.rt-top-toolbar-portal {');
  expect(css).toContain('position: fixed;');
  expect(css).toContain('.rt-floating-controls-portal {');
  expect(css).toContain('.rt-floating-controls-portal .rt-col-top-add-button,');
  expect(css).toContain('.rt-editor-shell {');
  expect(css).not.toContain('padding-right: var(--rt-col-edge-lane-width, 36px);');
  expect(css).toContain('min-height: 0;');
  expect(css).toContain('width: fit-content;');
  expect(css).toContain('min-width: var(--rt-track-min-width, 100%);');
  expect(css).toContain('.rt-editor {');
  expect(css).toContain('--rt-body-font-size: 13.5px;');
  expect(css).toContain('--rt-body-line-height: 1.8;');
  expect(css).toContain('--rt-body-text-color: #0D0D0D;');
  expect(css).toContain('--rt-list-marker-column: 28px;');
  expect(css).toContain('--rt-list-marker-gap: 4px;');
  expect(css).toContain('--rt-bullet-marker-size: 20px;');
  expect(css).toContain('.rt-editor code {');
  expect(css).toContain('border-radius: 6px;');
  expect(css).toContain('background: rgba(241, 245, 249, 0.9);');
  expect(css).toContain('color: #1d4ed8;');
  const tableWrapperBlock = css.match(/\.rt-editor \.tableWrapper \{[\s\S]*?\n\}/);
  expect(tableWrapperBlock?.[0]).toContain('display: inline-block;');
  expect(tableWrapperBlock?.[0]).toContain('width: fit-content;');
  expect(tableWrapperBlock?.[0]).toContain('min-width: 0;');
  expect(tableWrapperBlock?.[0]).not.toContain('min-width: var(--rt-table-min-width, auto);');
  expect(tableWrapperBlock?.[0]).not.toContain('width: 100%;');
  expect(css).toContain('.rt-editor ul {');
  expect(css).toContain('list-style: none;');
  expect(css).toContain('.rt-editor ol {');
  expect(css).toContain('list-style: none;');
  expect(css).toContain('.rt-editor ul,');
  expect(css).toContain('.rt-editor ul[data-type="taskList"] {');
  expect(css).toContain('margin: 0;');
  expect(css).toContain('padding-inline-start: 0;');
  expect(css).toContain('font-size: var(--rt-body-font-size);');
  expect(css).toContain('line-height: var(--rt-body-line-height);');
  expect(css).toContain('color: var(--rt-body-text-color);');
  expect(css).toContain('.rt-editor ul[data-type="taskList"] {');
  expect(css).toContain('.rt-editor ul[data-type="taskList"] > li {');
  expect(css).toContain('align-items: center;');
  expect(css).toContain('.rt-editor ul[data-type="taskList"] > li > label {');
  expect(css).toContain('min-width: calc(var(--rt-list-marker-column) - var(--rt-list-marker-gap));');
  expect(css).toContain('padding-right: var(--rt-list-marker-gap);');
  expect(css).toContain('.rt-editor ul[data-type="taskList"] > li > label > input[type="checkbox"] {');
  expect(css).toContain('width: 14px;');
  expect(css).toContain('height: 14px;');
  expect(css).toContain('margin: 0;');
  expect(css).toContain('.rt-editor ul[data-type="taskList"] > li > div {');
  expect(css).toContain('flex: 1 1 auto;');
  expect(css).toContain('min-width: 0;');
  expect(css).toContain('.rt-editor ul:not([data-type="taskList"]) > li,');
  expect(css).toContain('.rt-editor ol > li {');
  expect(css).toContain('display: grid;');
  expect(css).toContain('grid-template-columns: calc(var(--rt-list-marker-column) - var(--rt-list-marker-gap)) minmax(0, 1fr);');
  expect(css).toContain('column-gap: var(--rt-list-marker-gap);');
  expect(css).toContain('align-items: baseline;');
  expect(css).toContain('list-style: none;');
  expect(css).toContain('.rt-editor ul:not([data-type="taskList"]) > li > *,');
  expect(css).toContain('.rt-editor ol > li > * {');
  expect(css).toContain('grid-column: 2;');
  expect(css).toContain('.rt-editor ul:not([data-type="taskList"]) > li::before {');
  expect(css).toContain("content: '•';");
  expect(css).toContain('color: #2563eb;');
  expect(css).toContain('justify-self: center;');
  expect(css).toContain('align-self: baseline;');
  expect(css).toContain('font-size: var(--rt-bullet-marker-size);');
  expect(css).toContain('line-height: 1;');
  expect(css).toContain('.rt-editor ol {');
  expect(css).toContain('counter-reset: rt-ordered-list;');
  expect(css).toContain('.rt-editor ol > li {');
  expect(css).toContain('counter-increment: rt-ordered-list;');
  expect(css).toContain('.rt-editor ol > li::before {');
  expect(css).toContain("content: counter(rt-ordered-list) '.';");
  expect(css).toContain('justify-self: center;');
  expect(css).toContain('align-self: baseline;');
  expect(css).toContain('font-variant-numeric: tabular-nums;');
  expect(css).toContain('.rt-editor table {');
  expect(css).toContain('width: fit-content;');
  expect(css).toContain('min-width: var(--rt-table-min-width, 100%);');
  expect(css).toContain('.rt-editor th,');
  expect(css).toContain('.rt-editor td {');
  expect(css).toContain('border: 1px solid #e2e8f0;');
  expect(css).toContain('.rt-editor th {');
  expect(css).toContain('background: #f8fafc;');
  expect(css).toContain('.rt-top-toolbar {');
  expect(css).toContain('position: relative;');
  expect(css).toContain('transform: translateY(0);');
  expect(css).toContain('flex-shrink: 0;');
  expect(css).not.toContain('margin: 0 0 10px 0;');
  expect(css).not.toContain('padding-bottom: 28px;');
  expect(css).toContain('.rt-container .bn-extend-button-add-remove-columns,');
  expect(css).toContain('.rt-container .bn-extend-button-add-remove-rows {');
  expect(css).toContain('display: none !important;');
  expect(css).toContain('.rt-table-grip.row {');
  expect(css).toContain('.rt-table-grip.col {');
  expect(css).toContain('.rt-col-top-add-button {');
  expect(css).toContain('.rt-add-col-handle {');
  expect(css).toContain('.rt-add-row-handle {');
  expect(css).not.toContain('transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1);');
  expect(css).toContain('transition: transform 0.2s cubic-bezier(0.16, 1, 0.3, 1),');
  expect(css).not.toMatch(/\.rt-add-col-handle:hover,\s*\.rt-add-row-handle:hover\s*\{[^}]*scale\(/s);
  expect(css).toContain('.rt-mini-text {');
  expect(css).toContain('white-space: nowrap;');
});
